// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Article struct {
	ID        uuid.UUID
	Slug      string
	Author    string
	Content   pqtype.NullRawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Username  string
	Password  string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt time.Time
}
